### ISSUE TITLE
MacOS build issues with re2 version from setup

### ISSUE THREAD

**Issue by czentgr** [facebookincubator/velox#10154]
### Bug description

The build on MacOS fails where it is expected to succeed.
This occurs when trying to build changed from https://github.com/facebookincubator/velox/pull/10129 (thanks to @minhancao  for identifying the PR) with the following errors

```
In file included from /Users/czentgr/gitspace/velox/velox/functions/lib/tests/Re2FunctionsTest.cpp:16:
/Users/czentgr/gitspace/velox/./velox/functions/lib/Re2Functions.h:373:28: error: use of undeclared identifier 're2'
    const auto re2String = re2::StringPiece(string.data(), string.size());
                           ^
/Users/czentgr/gitspace/velox/./velox/functions/lib/Re2Functions.h:378:5: error: use of undeclared identifier 're2'
    re2::StringPiece subMatches[1];
    ^
2 errors generated.
```

The workaround is to use the re2 version from the bundle by setting
```
export re2_SOURCE=BUNDLED
```
until the setup script is fixed and the new version can be installed into the system.

It turns out that the installed version of re2 from the `setup-macos.sh` script does not match the bundled version (which is newer) - `2021-04-01` vs `2022-02-01`. The latter includes the undeclared identifiers.

### System information

n/a

**Comment by mbasmanova** [comment]
CC: @kgpai @zacw7

**Comment by mbasmanova** [comment]
CC: @majetideepak @assignUser

**Comment by majetideepak** [comment]
@czentgr has a fix open here https://github.com/facebookincubator/velox/pull/10155

**Comment by mbasmanova** [comment]
@czentgr @majetideepak 

I'm also seeing this failure in Benchmark CI. I wonder if it is due to old version of re2 installed in the Docker container used by that CI job.

https://github.com/facebookincubator/velox/actions/runs/9470910196/job/26092882241

Also, wonder why did we not see this before? re::StringPiece is also used in Re2Functions.cpp and that usage is not new.

**Comment by majetideepak** [comment]
It is a dependency problem since https://github.com/facebookincubator/velox/pull/10129 adds an re2 function to the header.

**Comment by majetideepak** [comment]
Starting with this change, https://github.com/facebookincubator/velox/pull/10129 we have a problem when we bundle DuckDB and use system RE2. This combination is conflicting with the DuckDB's RE2.
I was able to fix the benchmarks build by installing DuckDB.
https://github.com/facebookincubator/velox/pull/10158

**Comment by mbasmanova** [comment]
> This combination is conflicting with the DuckDB's RE2.

@majetideepak Deepak, thank you for looking into this issue. Would you elaborate a bit on what is the conflict? Is DuckDB including a version of RE2 that doesn't have re2::StringPiece defined? I saw a comment somewhere that newer RE2 may work with std::string_view and I wonder if we can simply replace re2::StringPiece with std::string_view.

Also, wondering if this issue is different from MacOS issue above.

**Comment by majetideepak** [comment]
@mbasmanova, duckdb source includes a copy of re2 as a third-party dependency. However, it defines the re2 headers as public which seem to conflict with the system RE2 header.
The MacOS issue above is the same.
I am trying another PR below which keeps the duckdb re2 headers private.
https://github.com/facebookincubator/velox/pull/10161

**Comment by majetideepak** [comment]
> work with std::string_view and I wonder if we can simply replace re2::StringPiece with std::string_view.

I think the fundamental problem of DuckDB re2 headers being exported as public needs to be resolved.

**Comment by mbasmanova** [comment]
@majetideepak Got it. Thank you for clarifying. Appreciate you help investigating and fixing this issue.
