### ISSUE TITLE
Presto window fuzzer test failed by Window frame offset value

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#11567]
### Description

```
E20241117 18:30:12.877318   591 Exceptions.h:66] Line: /__w/velox/velox/velox/velox/exec/fuzzer/PrestoQueryRunner.cpp:853, Function:fetchNext, Expression: response.status_code == 200 (0 vs. 200) GET from http://127.0.0.1:8080/v1/statement/queued/20241118_023011_00002_sdgbm/2?slug=x6cbae32fe19a48e6ad113de3f861f912&binaryResults=true failed: Operation timed out after 1001 milliseconds with 0 bytes received, Source: RUNTIME, ErrorCode: INVALID_STATE
E20241117 18:30:21.318113   591 Exceptions.h:66] Line: /__w/velox/velox/velox/velox/exec/fuzzer/PrestoQueryRunner.cpp:98, Function:throwIfFailed, Expression:  Presto query failed: 0 Window frame offset value must not be negative or null, Source: RUNTIME, ErrorCode: INVALID_STATE
E20241117 18:30:25.904656   591 Exceptions.h:66] Line: /__w/velox/velox/velox/velox/exec/fuzzer/PrestoQueryRunner.cpp:98, Function:throwIfFailed, Expression:  Presto query failed: 0 Window frame offset value must not be negative or null, Source: RUNTIME, ErrorCode: INVALID_STATE
/__w/_temp/550fbad8-d4d6-43c0-8d16-8cd42b04b6bc.sh: line 21:   591 Killed                  ./velox_window_fuzzer_test --seed ${RANDOM} --duration_sec $DURATION --minloglevel=0 --stderrthreshold=2 --log_dir=/tmp/window_fuzzer_repro/logs --repro_persist_path=/tmp/window_fuzzer_repro --enable_window_reference_verification --
```

https://github.com/facebookincubator/velox/actions/runs/11884148284/job/33113092277?pr=11534

**Comment by Yuhta** [comment]
This is still happening: https://github.com/facebookincubator/velox/actions/runs/12059777571/job/33629694422?pr=11671

**Comment by kagamiori** [comment]
The window fuzzer failures are caused by OOM during the fuzzer execution. I added some logs and found that at the beginning of ~Task(), the default memory pool (i.e., sysRoot_ pool) reports the peak memory usage of 3GB. Also, at the end of WindowFuzzer::go(), the WindowFuzzer's rootPool_ reports the peak memory usage of 6GB. Still investigating where the memory is taken.

**Comment by xiaoxmeng** [comment]
> The window fuzzer failures are caused by OOM during the fuzzer execution. I added some logs and found that at the beginning of ~Task(), the default memory pool (i.e., sysRoot_ pool) reports the peak memory usage of 3GB. Also, at the end of WindowFuzzer::go(), the WindowFuzzer's rootPool_ reports the peak memory usage of 6GB. Still investigating where the memory is taken.
> 
> Update: sysRoot_ pool was used in the CallbackSink when copying the result vector. The memory usage is large because the result of the window operation is an ARRAY<ARRAY> where every top-level array contains an average of 150 inner arrays. (Input of the window operation is also an ARRAY<ARRAY>, but every top-level array contains less than 20 inner arrays. The input vectors take 187MB, so it makes sense to me that the output vector takes 3GB.) The rootPool_ is used during the query execution and its memory usage is due to the same reason.

@kagamiori thanks for the analysis!

**Comment by aditi-pandit** [comment]
@kagamiori : Thanks for digging into this. Very curious what is the window function and SQL query here ?

Do you think this could be caused by the usage of prefix sort in Window now(https://github.com/facebookincubator/velox/pull/10417) ? This was added relatively recently. To test this more exhaustively I also changed the fuzzer key generation to build bigger keys.

**Comment by jinchengchenghh** [comment]
Thanks very much!
