### ISSUE TITLE
Mac build broken due to failed gtest submodule compilation using clang

### ISSUE THREAD

**Issue by dingqiaoyi** [facebookincubator/velox#1339]
$ clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

The version of gtest changed to be release-1.10.0 seems to be the cause.

**Comment by Dream-hu** [comment]
**new submodule gtest compile failed with clang 1.10.1 because of undeclared identifiers**
some error messages：
cmake --build _build/release -j 8
[536/818] Building CXX object third_party/googletest/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
FAILED: third_party/googletest/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o 
.../third_party/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:145:21: error: use of undeclared identifier 'Int64'
GMOCK_DECLARE_KIND_(Int64, kInteger);
                    ^
/third_party/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:146:21: error: use of undeclared identifier 'UInt64'
GMOCK_DECLARE_KIND_(UInt64, kInteger);
                    ^
/third_party/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:199:14: error: no template named 'bool_constant'
    : public bool_constant<

/third_party/googletest/googlemock/src/gmock.cc:47:1: error: no type named 'Int32' in namespace 'testing::internal'
GMOCK_DEFINE_int32_(default_mock_behavior, 1,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

9 errors generated.
[543/818] Building CXX object velox/external/duckdb/CMakeFiles/duckdb.dir/duckdb.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [build] Error 1
make: *** [release] Error 2

**Comment by mbasmanova** [comment]
CC: @wenleix @mshang816

**Comment by mbasmanova** [comment]
@dingqiaoyi A recent PR #1325 upgraded gtest to 1.11. Would you rebase onto latest main and retry?

CC: @kgpai @kagamiori

**Comment by mbasmanova** [comment]
@dingqiaoyi Have you tried rebasing onto latest main which uses gtest 1.11? Do you still see the issue?

**Comment by dingqiaoyi** [comment]
> @dingqiaoyi Have you tried rebasing onto latest main which uses gtest 1.11? Do you still see the issue?

@mbasmanova  
Now I cloud successfully build the project on my Mac using the main branch staying at this commit
https://github.com/facebookincubator/velox/commit/9d2ae599ad56d2837089b99cd6406185c4bd487b
I believe the PR https://github.com/facebookincubator/velox/pull/1325 works. I will try the lasted main.
