### ISSUE TITLE
Any plan to implement  combine_hash and hash_code?

### ISSUE THREAD

**Issue by yvxiang** [facebookincubator/velox#1340]
I try to connect presto with velox，and find that it doesn't work when with group by statement. Because $operator$hash_code and presto.default.combine_hash is not implement yet. So do we have any plan to support it ?

**Comment by mbasmanova** [comment]
I suggest to SET SESSION optimize_hash_generation=false. This will change the query plan to not require computing these hashes.

**Comment by mbasmanova** [comment]
@yvxiang Yang, have you tried setting session property optimize_hash_generation=false ? Did that resolve the issue you were seeing?

**Comment by yvxiang** [comment]
Yes， It works now.    Myabe I'll implement combine_hash and hash_code sometime:)

**Comment by mbasmanova** [comment]
Nice to hear you are unblocked. To clarify, we specifically do not want to use optimize_hash_generation optimization with Prestissimo/Velox because Velox may uses array-based aggregation and join as well as normalized keys. You can read more about these in https://facebookincubator.github.io/velox/develop/aggregations.html
