### ISSUE TITLE
Precision and scale variables in Decimal type signatures are not declared in function signatures 

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#2534]
Decimal type signatures in a function signature often come with a precision and a scale variables. But currently, these variables are not declared when building the function signature, neither through `FunctionSignatureBuilder` nor through the `registerFunction` API. SignatureBinderTest.cpp contains an example as follows. The variables `a_precision`, `a_scale`, `b_precision`, and `b_scale` are neither contained in `signature.variables_` nor in `signature.typeVariableConstants_`.
```
auto signature =
        exec::FunctionSignatureBuilder()
            .returnType("decimal(r_precision, r_scale)")
            .argumentType("decimal(a_precision, a_scale)")
            .argumentType("DECIMAL(b_precision, b_scale)")
            .variableConstraint(
                "r_precision",
                "min(38, max(a_precision - a_scale, b_precision - b_scale) + max(a_scale, b_scale) + 1)")
            .variableConstraint("r_scale", "max(a_scale, b_scale)")
            .build();
```

These undeclared variables are added into SignatureBinder::variables_ and checked for correctness (e.g., two different values cannot bind to the same variable) during SignatureBinder::tryBind() when the types to be bound are Decimal (introduced in https://github.com/facebookincubator/velox/pull/2278).
https://github.com/facebookincubator/velox/blob/40cbb262429d4cc7e634fd644f94c737ce82ff2f/velox/expression/SignatureBinder.cpp#L143-L165

We wonder whether it make sense to declare these variables when building the function signature and keep them in a list in FunctionSignature (e.g., similar to what we do for `K` and `V` in `map(K, V)`)? Also, it may be beneficial to generalize the logic of the correctness check of these variables such that the check applies to other future types that contain variables in them as well?

CC @mbasmanova, @majetideepak

**Comment by mbasmanova** [comment]
Here is some relevant documentation from Substrait: https://substrait.io/expressions/scalar_functions/#parameterized-types

**Comment by majetideepak** [comment]
@kagamiori @mbasmanova For templated signatures `array(T)` and Map `map(K, V)`, we add them to variables because they need to resolve to Velox types. The SignatureBinder logic treats them as `bindings`. For decimals, that is not the case. The variables are always constants and their inference logic is different. They are not bindings. We felt the explicit declaration `typeVariable("a_precision")` is redundant. They however are present in the argument TypeSignature.

![Screen Shot 2022-09-14 at 12 23 41 AM](https://user-images.githubusercontent.com/5091159/190060135-84ba1240-29e3-4234-bf2c-697bd2d4505f.png)

Do you have a particular use case that you are trying to solve?

**Comment by majetideepak** [comment]
@kagamiori I slept over this and I like your idea to generalize the logic of the correctness check of these variables. Let me take a stab at this.

**Comment by majetideepak** [comment]
@laithsakka If you are referring to this PR https://github.com/facebookincubator/velox/pull/2278, we only need the signature to be strongly typed for scalar functions. The strongly typed signatures are automatically added in the TypeAnalysis phase.
We need this because we register scalar functions for both `UnscaledShortDecimal` and `UnscaledLongDecimal` native types.  We need the strong type to pick one.
