### ISSUE TITLE
TPC-H connector must use Date type for date columns

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#2618]
The current implementation uses VARCHAR for date columns.
It will be nice to use Date type since Velox supports Date type and it will help 
TPC-H queries that use date functions like year() in Q7, Q8, Q9 without any changes.
Presto Java TPC-H connector uses the `date` type as well.

**Comment by Mionsz** [comment]
@majetideepak  So from documentation it seems like it does not matter how will you do it, but you muse be able to write date in YYYY-MM-DD decimal format, allow filtering, ranges etc. in that format. What is being done with the value itself does not matter. Correct me if I am wrong.
-----

**Spec:** https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v3.0.1.pdf
**Page 14:**
> Date is a value whose external representation can be expressed as YYYY-MM-DD, where all characters
are numeric. A date must be able to express any day within at least 14 consecutive years. There is no
requirement specific to the internal representation of a date.

-----
And as a good example we can use parquet file format, as it stores `DATE` following bellow spec:
- **Apache Parquet DATE type**
- **Logical Type:** `DATE`
- **Physical Type:** `INT32`
- **Description:** The `INT32` value represents the number of days since the Unix epoch (January 1, 1970), and `null` values are imported as `NaT`.

---
And as far as I remember there are some cases when the transition from/to varchar is being made under-the-hood.

**Comment by majetideepak** [comment]
@Mionsz thanks for the clarification. I just happened to post an old link. There are no constraints on the Velox side.
As you pointed out, the TPC-H spec does not mandate an internal representation for date. So this is not a bug.
However, using Date type will give us parity with Presto Java and allow us to use TPC-H queries that use date functions like `year() in Q7, Q8, Q9` without any changes.
Velox supports Date type, so this should be a nice improvement.
We do convert date to VARCHAR when writing DWRF columns since DWRF does not support the date type.
