### ISSUE TITLE
Guard mem copy from string views in Velox code.

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#2865]
https://en.cppreference.com/w/cpp/string/byte/memcpy

```If either dest or src is an [invalid or null pointer](https://en.cppreference.com/w/cpp/language/pointer#Pointers), the behavior is undefined, even if count is zero.```

we use memcpy to copy  from strings alot in our code, when the size of the string is 0 its undefined behaviour we need to fix that.

**Comment by pzhzqt** [comment]
https://github.com/facebookincubator/velox/blob/fd5958eca0db795b58577f51de41e798b8c1a8f8/velox/type/StringView.h#L53
Apart from this ctor, the logic in `StringView` made sure `data()` always return a valid ptr. And this ctor looks weird and I don't understand what the result represent.
If this ctor turns out to not produce a valid `StringView`, then a better solution is probably to just remove/replace it rather than modifying `memcpy`.

**Comment by pzhzqt** [comment]
> https://github.com/facebookincubator/velox/blob/fd5958eca0db795b58577f51de41e798b8c1a8f8/velox/type/StringView.h#L53
> 
> 
> Apart from this ctor, the logic in `StringView` made sure `data()` always return a valid ptr. And this ctor looks weird and I don't understand what the result represent.
> If this ctor turns out to not produce a valid `StringView`, then a better solution is probably to just remove/replace it rather than modifying `memcpy`.

https://github.com/facebookincubator/velox/blob/fc0f964e81cc784586f2caaf5220e9c61b276aba/velox/functions/prestosql/aggregates/ApproxDistinctAggregate.cpp#L182 is the only place I found using that ctor, and here the use makes sense: it's effectively a string buffer, and it ensured the size is an inline size, which means `data()` will return `prefix_`. So maybe the solution is to add an assert to that ctor so it can only be called on an inlined size?
