### ISSUE TITLE
the Compile Problem has made me crazy!

### ISSUE THREAD

**Issue by zuochunwei** [facebookincubator/velox#2950]
when I executed `scripts/setup-macos.sh`, the output messages showed as follows:
```
Installing: /usr/local/lib/libdouble-conversion.a
```

I checked the directory `/usr/local/lib/` that file `libdouble-conversion.a` was created, and the file `/usr/local/lib/libdouble-conversion.dylib` was not created according to the output messages.

when I typed `make` to create Velox, then the following error messages generated:
```
cmake --build _build/release -j 12
ninja: error: '/usr/local/lib/libdouble-conversion.dylib', needed by 'velox/buffer/tests/velox_buffer_test', missing and no known rule to make it
make[1]: *** [build] Error 1
make: *** [release] Error 2
```

why the `make` command referenced `/usr/local/lib/libdouble-conversion.dylib` instead of `/usr/local/lib/libdouble-conversion.a`? 

the script function of `install_double_conversion` installed double_conversion lib under the dir of `/usr/local/lib/`, the following `make` command used `/usr/local/lib/libdouble-conversion.dylib`.

that is very confusing!

=== pic
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/7720380/197730627-70008365-49f9-49de-be47-63391085bcbf.png">

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/7720380/197730641-49102eec-f68b-4e48-be75-79b5ed9d5d30.png">

**Comment by kgpai** [comment]
Hi @zuochunwei , 

Typically building , installing double conversion should produce an archive file and not a dylib (Since the install shows .a, I think this checks out).  However it seems that here velox is trying to link against a double-conversion dylib, that means it was probably installed via other means or CMake is finding a shared lib double conversion. One way to verify this is by adding `set(CMAKE_FIND_DEBUG_MODE TRUE)` to the root CMakeLists.txt file and seeing which double-conversion is picked by find package. If you make this change and paste the cmake output we might be able to help you root cause it. 

Also we are working to have more hermetic builds and we would love any contributions . If you are interested in removing double-conversion from the setup process , please let me know.

**Comment by amorynan** [comment]
Hello , I have meet same problem here, and set(CMAKE_FIND_DEBUG_MODE TRUE) as well, any help can I get ?

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/18551114/205182248-d570962a-3249-44e4-8331-ff555a1dbda8.png">

**Comment by kgpai** [comment]
Hi @amorynan , We have a new improved issue process, that requests logs and also requires a script is run to gather system information. All of that helps us gather information on how to make an informed decisions to troubleshoot your problems. Can you thus create a new issue and fill it up so we have all the information we need to help you ?
Thanks !

**Comment by amorynan** [comment]
https://github.com/facebookincubator/velox/issues/3400 here I make

**Comment by assignUser** [comment]
@zuochunwei please check this comment https://github.com/facebookincubator/velox/issues/3400#issuecomment-1336197659 it should solve the issue. 

If not please continue in #3400 as its the same issue.
