### ISSUE TITLE
Different results:  array_position(array_intersect(map_values

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3045]
This is probably due to the order of elements in the array returned by array_intersect is not deterministic. The order may be different if inputs are flat vs. constant.

Repro files:

[array-intersect.tar.gz](https://github.com/facebookincubator/velox/files/9906088/array-intersect.tar.gz)

```
I1031 18:48:38.255223 1509498 ExpressionFuzzer.cpp:702] ==============================> Started iteration 1807 (seed: 1984411202)
I1031 18:48:38.257859 1509498 ExpressionVerifier.cpp:141] Executing expression: array_position(array_intersect(map_values(10 elements starting at 90 {-4952515-08-11 => [90->247] [247->81]
 1, 3392378-06-20 => [91->123] null, 1656781-04-09 => [92->135] [135->31] 0, -455575-03-26 => null, 3310935-09-01 => [94->221] [221->163] 1, ...}),10 elements starting at 110 {[110->243]
[243->320] [320->422] 0, [111->306] [306->665] [665->536] 1, [112->185] [185->191] [191->599] 1, null, [114->522] [522->779] [779->56] 0, ...}),0)
I1031 18:48:38.258031 1509498 ExpressionVerifier.cpp:144] 0 vectors as input:
E1031 18:48:38.265197 1509498 Exceptions.h:68] Line: velox/expression/tests/ExpressionVerifier.cpp:129, Function:compareVectors, Expression: left->equalValueAt(right.get(), i, i) Different results at idx '0': '1' vs. '3', Source: RUNTIME, ErrorCode: INVALID_STATE
I1031 18:48:38.266067 1509498 ExpressionVerifier.cpp:311] Persisted input: --input_path /tmp/a/velox_vector_LaJ30L --sql_path /tmp/a/velox_sql_siRa34
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Different results at idx '0': '1' vs. '3'
Retriable: False
Expression: left->equalValueAt(right.get(), i, i)
Function: compareVectors
File: velox/expression/tests/ExpressionVerifier.cpp
Line: 129
```

**Comment by laithsakka** [comment]
@mbasmanova  so do we  have to make it deterministic?

**Comment by mbasmanova** [comment]
@laithsakka That's a good question. It would be great if we can make array_intersect deterministic without a performance hit. This would allow us to use Fuzzer for testing. If that's not possible or performance hit is too big, we have 2 options: (1) exclude this function from testing or (2) enhance the Fuzzer to allow for different order of elements when comparing arrays.

**Comment by laithsakka** [comment]
In general F14HashMap is not deterministic with respect to the order anyway, would it make sense to mark this function 
as non-deterministic ? @mbasmanova

**Comment by mbasmanova** [comment]
> would it make sense to mark this function as non-deterministic?

@laithsakka That's a good question. I assume you are referring to array_intersect function. In Presto, this function is deterministic. At least it is not marked as non-deterministic. Can we change the implementation to make array_intersect deterministic?

**Comment by pedroerp** [comment]
> In general F14HashMap is not deterministic with respect to the order anyway, would it make sense to mark this function as non-deterministic ? @mbasmanova

It doesn't seem like the problem is related to f14map ordering, since it's only used to validate whether an element is part of the intersection or not. The issue, like Masha pointed out at first, is related to constant optimizations, which maybe results in us swapping the left and right sides of the inputs and hence changing the output.

**Comment by pedroerp** [comment]
I spend some time thinking about this I couldn't find an optimal solution that gives us determinism without any perf changes. These are some of of the options we can consider:

1. Assume this function will be non-deterministic.
2. Disable the constant optimization for when the constant array is the first parameter. This is likely the best option, as the intuition is that users would likely provide a constant array as a second argument (`array_intersect(col, ARRAY['a', 'b'])` and not `array_intersect(ARRAY['a', 'b'], col)`). This is easy to fix, makes it deterministic and keep the same level of efficiency.
3. We can add a quick step ad the end to sort the array contents, at the cost of some overhead nad further deviating from the java implementation.
4. We can consider changing the implementation of this function to first sort all arrays, then just "merging-sorting" them. This would require us to pretty much re-write the full thing though.

I checked the Presto java implementation and it provides determinism since it doesn't implement any constant input optimizations like we do.

**Comment by mbasmanova** [comment]
@pedroerp Pedro, thank you for looking into this. I feel option 2 is the most practical. It would be nice to add a comment in the code to explain why we do not optimize for the case when first array is constant.

That said, I think the semantics on the Presto function are wrong. It seems strange that array_intersect(a, b) may not be the same as array_intersect(b, a). I'd expect array_intersect to declare itself non-deterministic and explain that the order of elements in the result array may be different, i.e. array_sort(array_intersect(a, b)) is deterministic and array_sort(array_intersect(a, b)) == array_sort(array_intersect(b, a)).

**Comment by pedroerp** [comment]
Left-hand side constant optimization disabled in #4390. array_intersect() re-enabled in expression fuzzer.
