### ISSUE TITLE
Crash in approx_percentile

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3099]
To reproduce, run single aggregation `approx_percentile(c0, c1, c2)` on the attached vector.

[approx_pct.tar.gz](https://github.com/facebookincubator/velox/files/9940333/approx_pct.tar.gz)

**Comment by Yuhta** [comment]
The 'arrays->elements()' below is a dictionary encoded vector, hence, a cast to flat vector returns nullptr.

```
    } else if (decoded.base()->typeKind() == TypeKind::ARRAY) {
      isArray = true;
      auto arrays = decoded.base()->asUnchecked<ArrayVector>();
      auto elements = arrays->elements()->asFlatVector<double>();
      data = elements->rawValues() + arrays->offsetAt(i);
```

**Comment by Yuhta** [comment]
This is generated by parsing from a constant expression.  I will double check where all these constant exprs coming from and how they get parsed.  If it’s all generated in our code we can exclude some encoding combination for these arguments in fuzzer.  Otherwise I will just harden the function implementation.
