### ISSUE TITLE
AggregateWindowFunction needs to call Aggregate::finalize

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3292]
Some aggregate functions require a call to Aggregate::finalize() before extractAccumulators or extractValues. An example would be map_agg or array_agg. This implies that `fixedStartAggregation` optimization cannot be applied as-is to such functions. 

Also, Aggregate::extractXxx expects an all-flat result vector, but may produce a non-flat one. map_agg produced a MapVector with dictionary-encoded keys (see MapAggregateBase::removeDuplicates).

See https://github.com/facebookincubator/velox/pull/3291 for repro.

Functions that require finalize:
- array_agg
- map_agg
- approx_percentile

**Comment by mbasmanova** [comment]
CC: @Yuhta

**Comment by mbasmanova** [comment]
Array_agg and map_agg require finalize because they use ValueList which requires finalize. I think we can modify ValueList to not require finalize and therefore remove this requirements from array_agg and map_agg. 

@Yuhta Jimmy, is finalize essential for approx_percentile? Or, would that aggregate function allow calling finalize, then extract, then add some more data, finalize, extract, etc?

**Comment by Yuhta** [comment]
In `approx_percentile`, `finalize` does 2 things:

1. We buffer large count values instead of adding them directly to sketch immediately.  In `finalize` we flush all buffered large count values into the sketch.  This is more efficient than adding them one by one.
2. We compact the sketch in `finalize`, so that the memory usage can be reduced when we serialize them and especially later when the final aggregation node receives a lot of them.

1 is functionally necessary and 2 is an optimization and can be skipped in some cases.  We could have a `fastFinalize` and only do 1 in that case.  It can be called like `finalize`, `extract`, add more, `finalize`, `extract`, ...  The performance depends on how often you extract.

**Comment by mbasmanova** [comment]
> It can be called like finalize, extract, add more, finalize, extract, ... 

@Yuhta Just to clarify, does approx_pct already supports this pattern or would it need to be modified to support this?

**Comment by Yuhta** [comment]
@mbasmanova It already supports this pattern

**Comment by mbasmanova** [comment]
@Yuhta Jimmy, thank you for clarifying.

I propose the following:

- remove Aggregate::finalize() API
- document that aggregate functions must support the pattern of add-extract-add-extract-...

Any objections?
