### ISSUE TITLE
Different version defined for Protobuf

### ISSUE THREAD

**Issue by leoluan2009** [facebookincubator/velox#3736]
### Bug description

We have different version defined for Protobuf:
`resolve_dependency(Protobuf 3.21.4)` in https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L382

`set(VELOX_PROTOBUF_BUILD_VERSION 21.4)` in https://github.com/facebookincubator/velox/blob/main/ThirdpartyToolchain.cmake#L96

is it a bug or expected behavior?

### System information

Velox System Info v0.0.2
Commit: cb861f4a389f6778717f5dfad14cc7c8752ea107
CMake Version: 3.25.1
System: Darwin-21.5.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 13.1.6.13160021
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 13.1.6.13160021
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.25.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by leoluan2009** [comment]
cc @pedroerp @kgpai

**Comment by mbasmanova** [comment]
CC: @raulcd

**Comment by leoluan2009** [comment]
Hi @mbasmanova @raulcd, if this is a bug, I can create a PR to fix it. And then we can resolve https://github.com/facebookincubator/velox/pull/3721#discussion_r1072309829 by remove `option cc_enable_arenas = true;` , since after Protobuf version 3.14.0 cc_enable_arenas no longer has any effect in [the release notes for 3.14.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0):

Arenas are now unconditionally enabled. cc_enable_arenas no longer has
any effect.

**Comment by raulcd** [comment]
sorry I am the release manager for the new Apache Arrow 11.0.0 release and I am trying to fix some of the issues there. I might take a little longer than usual to be able to investigate if this is an issue or is expected behaviour. I remember protobuf changed their release versioning scheme. Before was using the schema 3.20.x but they moved to 21.x, even though they still use both tags for 3.21.x and 21.x see here: https://github.com/protocolbuffers/protobuf/tags
Probably `find_package` is able to find with `3.21.4` but we download the tag `21.4` if bundled from source but I would have to investigate further.

**Comment by leoluan2009** [comment]
Hi @raulcd, thanks for your information!

**Comment by mbasmanova** [comment]
> since after Protobuf version 3.14.0 cc_enable_arenas no longer has any effect

That's nice.

@raulcd Thank you for your help.

**Comment by majetideepak** [comment]
This is just the Protobuf release naming nuance.
