### ISSUE TITLE
map function crashes while setting values

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#3994]
### Description

results in a segfault. happens while setting a null in the nulls buffer. I checked the capacity of the buffer and it seems the position being written into is a valid memory location. need to drill in more to see what is happening.

### Error Reproduction

[spark_map_crash_repro.zip](https://github.com/facebookincubator/velox/files/10690574/spark_map_crash_repro.zip)

**Comment by kagamiori** [comment]
Spark map function uses Presto's map function implementation in Velox, so remove the label "spark-functions" as it's not specific to spark.

**Comment by laithsakka** [comment]
Looking at this it looks like the crash is in the destructor of the expression set?

**Comment by laithsakka** [comment]
there are to problems here:

1. For common path the destructor of the exprSet crash.

2. for simplified the reading the null in the map function is crashing

**Comment by laithsakka** [comment]
For the simplified path bug the bug is in DecodedVector when the input is Dictionary over constant bool vector.
What happens is that the code will set data_ to the address of the boolean field in the constant vector (address of a boolean variable)
Then we try to read it using valueAt 
we   read bits::isBitSet(reinterpret_cast<const uint64_t*>(data_), index(idx));
but that does not work in this case since data_ is not an to  uint64_t* !

**Comment by laithsakka** [comment]
@singcha I put a fix for this. I hope you did not spend long time on this.
