### ISSUE TITLE
min_by and max_by Presto aggregates do not process extreme values correctly

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#5145]
### Bug description

These aggregates initialize accumulators with min and max values, then update the accumulator only if input is > or < than current value. Thus, they fail to update the values if inputs are themselves equal to min or max.

CC: @majetideepak @bikramSingh91 @kagamiori @laithsakka @kgpai 

Simple repro:

```
TEST_F(MinMaxByComplexTypes, limits) {
  static const auto kMax = std::numeric_limits<int64_t>::max();
  static const auto kMin = std::numeric_limits<int64_t>::min();
  auto data = makeRowVector({
      makeFlatVector<int64_t>({1, 2}),
      makeFlatVector<int64_t>({kMin, kMin}),
  });

  createDuckDbTable({data});

  testAggregations(
      {data},
      {},
      {"min_by(c0, c1)", "max_by(c0, c1)"},
      "SELECT min_by(c0, c1), max_by(c0, c1) FROM tmp");
}
```

### System information

n/a

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng @spershin @amitkdutta @vermapratyush

**Comment by mbasmanova** [comment]
CC: @aditi-pandit

**Comment by Yohahaha** [comment]
This issue is caused by the `initialValue_`, it will be set to accumulator when initialization.
https://github.com/facebookincubator/velox/blob/9cbee26a68f49538b0019ff021482c169e1f5186/velox/functions/prestosql/aggregates/MinMaxByAggregates.cpp#L172-L174

For above test, `initialValue_` is kMin, the reason for wrong result of min_by is current implementation use a strictly comparator, every coming value in lessThan(newValue, oldValue) return false, so accumulator will never be updated.

Use std::optional<T> as accumulator initial value may fix this problem.
```
if (accumulator.hasValue()) {
    compareAndUpdate();
} else {
    update();
}
```
CC @mbasmanova

**Comment by mbasmanova** [comment]
@Yohahaha Thank you for taking a look. Would you like to submit a fix?

**Comment by Yohahaha** [comment]
> @Yohahaha Thank you for taking a look. Would you like to submit a fix?

Sure, I will fix it.
