### ISSUE TITLE
Error for NULL array handling in Reduce with coalesce as the output function

### ISSUE THREAD

**Issue by yma11** [facebookincubator/velox#5768]
### Bug description

`NULL` array and array with null elements are not the same. For `NULL` array, it may should not be passed to input/output function to avoid incorrect update of final result, like `coalesce` function.
This issue can be reproduced by UT like:
```
TEST_F(ReduceTest, nullArray) {
  auto arrayVector = makeNullableArrayVector<int64_t>(
      {std::nullopt, {{1, std::nullopt}}, {{std::nullopt, 2}}, {{1, 2, 3}}});
  auto data = makeRowVector({arrayVector});
  auto result = evaluate(
      "reduce(c0, 0, (s, x) -> s + x, s -> coalesce(s, 0) * 10)",
      data);
  assertEqualVectors(
      makeNullableFlatVector<int64_t>({std::nullopt, 0, 0, 60}), result);
}
```

### System information

N/A

**Comment by yma11** [comment]
@bikramSingh91 I noticed you have some insights and made some changes for `Reduce` function, any clue about how to fix this issue?

**Comment by bikramSingh91** [comment]
@yma11 
The root cause for this issue is that we are also evaluating null rows by passing them to the lambda, however, we should do something similar to how we handle nulls for null propagating functions in Expr.cpp, that is, we only evaluate null rows in the lambdas and add nulls to the final result at the end. We can do this by creating a LocalSelectivityVector applyRows and set it correctly with non Null rows (see this for reference: https://github.com/facebookincubator/velox/blob/main/velox/expression/FieldReference.cpp#L56-L63 )
Then use this moving forward from L103 and L160. Finally we add the nulls to 'result' using result->addNulls(flatArray->rawNulls(), rows);

A question might arise here as to why we don’t just leverage the default null behavior handling in expr.cpp, a good reason for that is explained here: https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/Reduce.cpp#L57-L63

Another question can be is why we don’t just add nulls at the end, the reason for that is that we don’t even want those rows to be evaluated in case the lambdas run into issues on those rows when they are not even supposed to evaluate them, also it saves extra cycles for us by not evaluating those rows.
