### ISSUE TITLE
Implement ConstantVector to arrow array

### ISSUE THREAD

**Issue by Yuhta** [facebookincubator/velox#7189]
### Description

`TableWriterTest/UnpartitionedTableWriterTest` is failing because we don't have support to convert constant vector to arrow.  Either flatten it before pass it to the bridge or implement the RLE encoded arrow array for it.

https://app.circleci.com/pipelines/github/facebookincubator/velox/36289/workflows/4b86379e-27ff-44ba-8ffa-aa499e557570/jobs/240816/tests

See #7173

**Comment by czentgr** [comment]
@Yuhta please see https://github.com/facebookincubator/velox/pull/7025
This is a PR addressing dictionary and constant vectors for writing to Parquet.

For dictionary vectors parquet doesn't allow NULL values and there is a problem with partitioned data (index vector reuse) so it has to be flattened. The same code can be used for the constant vector.

**Comment by pedroerp** [comment]
@Yuhta @czentgr We have another internal project depending on constant vector support through the arrow bridge. My plan is to convert it using the new REE format in Arrow 14. @czentgr unless you have already started looking into this, feel free to re-assign this Issue to me.

**Comment by pedroerp** [comment]
Code out for review in:

https://github.com/facebookincubator/velox/pull/7327
https://github.com/facebookincubator/velox/pull/7392
https://github.com/facebookincubator/velox/pull/7398

**Comment by czentgr** [comment]
@pedroerp @majetideepak 
I tested the new addition with the TableWriter tests for Parquet where I'm adding the dictionary vector flattening. Looks like Velox needs to upgrade the Arrow code it is using because the C API did not support the REE encoding until https://github.com/apache/arrow/issues/37173 (about 3 months ago). On a side note, this isn't really documented for the C API.
Either way, we need to upgrade the Arrow dependency to Arrow 14 (currently 13).
If you are ok, I can take a stab since it is a blocker for my own PR to enable the parquet format for all TableWriter tests.

**Comment by pedroerp** [comment]
@czentgr I just upgraded it to 14.0.0 on this PR: https://github.com/facebookincubator/velox/pull/7412

I also noticed that the current docs don't describe the new options yet. The dev version of the docs contains it though:

https://arrow.apache.org/docs/dev/format/Columnar.html#run-end-encoded-layout

**Comment by pedroerp** [comment]
The only thing missing now is the opposite path (converting a REE arrow array into Velox), but I don't think this is necessary for TableWriter.

**Comment by czentgr** [comment]
@pedroerp @majetideepak After upgrading to Arrow 14 I found additional issues with attempting to write constant vectors to Parquet using the ArrowSchema with REE for constant.

I created issue https://github.com/facebookincubator/velox/issues/7457 for it.

It means that for my own PR I have to exclude the constant test when enabling Parquet in the writer test.

**Comment by majetideepak** [comment]
@czentgr thanks for investigating these issues. As planned, let's plan to convert encoded(dictionary, constant) vectors to flat vectors inside ArrowBridge and support ParquetWriter.

**Comment by felipecrv** [comment]
Hi everyone.

@majetideepak, if you expand a constant vector (an REE) when writing to Parquet, won't you have to always do that from now on? To ensure files written by Velox always have the same format given the same inputs.

I ask this because the plan for Apache Arrow when writing REEs to Parquet would be to write them as RLE-encoded Parquet arrays. This is not implemented yet, but now that I see a need for it, I can prioritize it more.

**Comment by majetideepak** [comment]
@felipecrv We could make the expansion a property of the Velox ParquetWriter to maintain consistent semantics.
 But it would be great if we could avoid this. 
We faced two issues 
1) Writing REE to Parquet. Do you have an estimate on when this would be ready? 
2) Dictionary with Null values are not supported. We get an error `NotImplemented: Writing DictionaryArray with null encoded in dictionary type not yet supported`
See https://github.com/apache/arrow/blob/73589ddd60e4cbcd860102871692541989ea38c6/cpp/src/parquet/arrow/path_internal.cc#L752

**Comment by pedroerp** [comment]
This is done now.
