### ISSUE TITLE
Allow marking an argument as constant in the simple function API

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#7877]
### Description

For details please see #3995.
cc @mbasmanova , @rui-mo , @laithsakka , @kagamiori .
Thanks.

**Comment by zhli1142015** [comment]
Here is my proposal for the change, please let me know if this looks ok to you, thanks.

1. define static const function to tell which argument is constant.
`static constexpr bool is_constant_arg(int32_t position)`
2. In [`buildSignature`](https://github.com/facebookincubator/velox/blob/main/velox/core/SimpleFunctionMetadata.h#L452) check if argument is constant. If yes, we call `constantArgumentType` for it.
```
    int32_t position = 0;
    for (const auto& arg : analysis.argsTypes) {
      if (udf_is_constant_arg<Fun>()(position)) {
        builder.constantArgumentType(arg);
      } else {
        builder.argumentType(arg);
      }
      position++;
    }
```

**Comment by mbasmanova** [comment]
I wonder if it would be possible to specify constness at the same time as type, e.g.

```
registerFunction<InFunction, bool, int32_t, Constant<Array<int32_t>>("in")
```

CC: @laithsakka

**Comment by zhli1142015** [comment]
> I wonder if it would be possible to specify constness at the same time as type, e.g.
> 
> ```
> registerFunction<InFunction, bool, int32_t, Constant<Array<int32_t>>("in")
> ```
> 
> CC: @laithsakka

Does this mean we need to define a type "Constant<T>"?

**Comment by laithsakka** [comment]
Constant<T> sounds like a simpler (from UDF auothoring point of view)
One way to support that is the following, on key point is that we want to avoid handling Constant all over the place
so we probably want to peal it off the types asap. 
Introduce the following classes:

```
// The constant type
template<typename T>
struct Constant {
};

// Remove constant layer. 
template <typename T>
struct UnwrapConstant {
  using type = T;
};

template <typename T>
struct UnwrapConstant<Constant<T>> {
  using type = T;
};

// Check if t is constant.
template <typename T>
struct isConstant {
  static constexpr bool  value = false;
};

template <typename T>
struct isConstant<Constant<T>> {
  static constexpr bool value = true;
};

// Can be used to check if an arg at index x is constant. 
template <typename ...TArgs>
struct ConstantChecker{
  static constexpr bool isConstant[sizeof...(TArgs)] = {   isConstant<TArgs>::value...};
};

int main()
{
    std::cout<<ConstantChecker<Constant<int>, int>::isConstant[0];
    std::cout<<ConstantChecker<Constant<int>, int>::isConstant[1];

    return 0;
}
```
https://onlinegdb.com/90ACLcCEr

Next We need to the do the following changes:
1. Add ConstantChecker as another template argument to UDFHolder.
```
template <typename Fun, typename Exec, typename TReturn, typename ConstantChecker, typename... TArgs>
class UDFHolder final
```

2. Add ConstantChecker as another template argument to SimpleFunctionMetadata. 
```
template <typename Fun, typename TReturn, typename ConstantChecker, typename... Args>
class SimpleFunctionMetadata :
```

3. Inside register function pass ConstantChecker and Unwrapped args. 
OLD:
```
  using funcClass = Func<exec::VectorExec>;
  using holderClass =
      core::UDFHolder<funcClass, exec::VectorExec, TReturn, TArgs...>;
  exec::registerSimpleFunction<holderClass>(aliases);
  ```
  NEW:
  ```
  using funcClass = Func<exec::VectorExec>;
  using holderClass =
      core::UDFHolder<funcClass, exec::VectorExec, TReturn, ConstantChecker<Args>,  UnwrapConstant<TArgs>::type...>;
  exec::registerSimpleFunction<holderClass>(aliases);
  ```
  
  4. Finally use ConstantChecker to check if we need to add the constant property as you proposed in TypeAnalysis in SimpleFunctionMetadata.
  
  This is not the only way to solve this problem, but i feel this could be the one of the easiest to implement since TArgs wont be changed and no other instantiations are effected.
