### ISSUE TITLE
Why implementation of Driver::runInternal is so complicated？

### ISSUE THREAD

**Issue by yvxiang** [facebookincubator/velox#812]
I checked out the implementation of  Driver::runInternal，it looks so complicated:

1. why not use coroutine to simplify the block of pyhsical thread
2. why not push data from bottom to top

Both 1 and 2 can make the code more easier, more maintainable, and also with high concurrency

**Comment by mbasmanova** [comment]
Hi @yvxiang,

thank you for the questions. 

(1) coroutines are available only in C++ 20, but Velox requires only C++ 17. 

(2) we want to allow for early termination by operators like Limit and Hash Join. Limit doesn't need to receive all its input before producing full output. As soon as it has seen N rows, it is done. Similarly, Hash Join can finish early if build side turns out to be empty. We also would like to allow for the downstream operators to apply back pressure and prevent production of too much data. The design there processing id driven by demand from the downstream operators satisfies these requirements.

Hope this helps. Let me know if I misunderstood your questions, my responses are not clear or you have follow-up questions.

**Comment by yvxiang** [comment]
OK，any plan to use coroutines in the future?
