### ISSUE TITLE
parse_datetime throws Invalid format exception for presto supported formats.

### ISSUE THREAD

**Issue by amitkdutta** [facebookincubator/velox#8386]
### Description

Presto supports following sytax:

```
presto:de> select parse_datetime('2024-01-14+17:00:99 UTC', 'yyyy-MM-dd+HH:00:99 ZZZ');
            _col0            
-----------------------------
 2024-01-14 17:00:00.000 UTC 
(1 row)
```

In Velox, such parsing throws exception

```
TEST_F(DateTimeFunctionsTest, parseTest) {
  evaluate<RowVector>(
      "parse_datetime(c0, 'yyyy-MM-dd+HH:00:99 ZZZ')",
      makeRowVector({makeNullableFlatVector<StringView>(
          {StringView{"2024-01-14+17:00:99 UTC"}})}));
}
```

Exception message is: 

```
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Invalid format: "2024-01-14+17:00:99 UTC" is malformed at "UTC"
Retriable: False
Context: parse_datetime(c0, yyyy-MM-dd+HH:00:99 ZZZ:VARCHAR)
Top-Level Context: Same as context.
Function: parseFail
File: fbcode/velox/functions/lib/DateTimeFormatter.cpp
```

**Comment by amitkdutta** [comment]
CC: @pedroerp @mbasmanova @zacw7

**Comment by mbasmanova** [comment]
CC: @aditi-pandit @majetideepak @duanmeng

**Comment by svm1** [comment]
I can look into this one, might be similar to some of the other timezone issues I've been looking at.

**Comment by svm1** [comment]
@amitkdutta @majetideepak @aditi-pandit 

Sorry for the delay, I have been occupied with other work. Took a look into this. The issue comes from the timezone formatting flag (`z` vs `Z`). If we consider two cases, identical in all regards except for the upper/lowercase timezone flag:

case A)
```
EXPECT_EQ(TimestampWithTimezone(1705251600000, util::getTimeZoneID("+00:00")), 
      parseDatetime("2024-01-14+17:00:99 UTC", "yyyy-MM-dd+HH:00:99 ZZZ"));
```
This statement fails, as seen above.

case B)
```
EXPECT_EQ(TimestampWithTimezone(1705251600000, util::getTimeZoneID("+00:00")), 
      parseDatetime("2024-01-14+17:00:99 UTC", "yyyy-MM-dd+HH:00:99 zzz"));
```
While this statement passes.

The issue comes from the way the format string is handled in `DateTimeFormatter.cpp`. The lowercase `z` is interpreted as being indicative of a _timezone abbreviation_ (`TIMEZONE` token), while an uppercase `Z` will be assumed to represent a _timezone offset_ (`TIMEZONE_OFFSET_ID` token). This happens at the point of tokenization of the input format string:

```
case 'z':
    builder.appendTimeZone(count);
    break;
 case 'Z':
    builder.appendTimeZoneOffsetId(count);
    break;
```

Presence of a `TIMEZONE` token directs processing to the `parseTimezone()` function, which attempts to map the input to the following three-letter timezone abbreviations:
```
static std::unordered_map<std::string_view, int64_t> defaultTzNames{
          {"UTC", 0},
          {"GMT", 0},
          {"EST", util::getTimeZoneID("America/New_York")},
          {"EDT", util::getTimeZoneID("America/New_York")},
          {"CST", util::getTimeZoneID("America/Chicago")},
          {"CDT", util::getTimeZoneID("America/Chicago")},
          {"MST", util::getTimeZoneID("America/Denver")},
          {"MDT", util::getTimeZoneID("America/Denver")},
          {"PST", util::getTimeZoneID("America/Los_Angeles")},
          {"PDT", util::getTimeZoneID("America/Los_Angeles")},
      };
```

On the other hand, presence of a `TIMEZONE_OFFSET_ID` token will direct processing to the `parseTimezoneOffset()` function, which maps input to any valid `+hh:mm` offset string. 

By definition from JodaTime's own format pattern documentation, the lowercase `z` is explicitly specified as the flag used for the three-letter abbreviations, while the uppercase `Z` is to be used for offsets (full names are unsupported). 

```
z       time zone                    text          Pacific Standard Time; PST
Z       time zone offset/id    zone          -0800; -08:00; America/Los_Angeles
 ```

I'm not sure why the uppercase `Z` successfully allows parsing of "UTC" in Java - undocumented/unaccounted behavior with JodaTime? 

The main question now is, do we want to fix this? The current Velox parsing implementation matches the by-the-book documentation, but this undocumented behavior is currently unsupported. 

If we do wish to support it, we would have to mark some clear distinction in the way `Z` is used, to avoid confusion between interpreting it as an offset token or as an alternate means of a three-letter-zone-abbreviating token. JodaTime seems to use the number of `Z`'s to distinguish between the specific interpretation of the flag (https://github.com/JodaOrg/joda-time/blob/290a451396637ed9ad52cce61e40382e8095d8fb/src/main/java/org/joda/time/format/DateTimeFormat.java). Currently, Velox's parser makes no use of the token length, so this could be a means to achieving this.

Please let me know what you guys think.

**Comment by svm1** [comment]
Resolved by Pedro - https://github.com/facebookincubator/velox/pull/8915.
