### ISSUE TITLE
Cast to decimal format is not supported.

### ISSUE THREAD

**Issue by amitkdutta** [facebookincubator/velox#8412]
### Description

Casting to decimal is a popular cast expression which isn't supported yet. Many presto queries cast different types to decimal (e.g. `select cast ('123.9092121' as decimal(10,3))`) which are failing due to this missing feature.

**Comment by amitkdutta** [comment]
CC: @mbasmanova @kagamiori @zacw7

**Comment by mbasmanova** [comment]
CC: @majetideepak @aditi-pandit @rui-mo @duanmeng

**Comment by majetideepak** [comment]
@karteekmurthys can you take a look? Don't we support this already?

**Comment by karteekmurthys** [comment]
I am able to run locally:

```
presto> select cast ('123.9092121' as decimal(10,3));
  _col0  
---------
 123.909 
(1 row)
```
I have disabled coordinator to be part of compute to make sure the request goes to C++ worker:
```
presto.version=testversion
node-scheduler.include-coordinator=false
use-alternative-function-signatures=true
optimizer.optimize-hash-generation=false
```
The above works because, coordinator treats the numeric literals as a decimal.
I checked code and we don't support VARCHAR to decimal conversion.

I could repro this issue creating a table with varchar column.
```
presto:test> select cast(c0 as decimal(5,2)) from t2;

Query 20240117_194523_00009_vsd8a, FAILED, 1 node
Splits: 2 total, 0 done (0.00%)
[Latency: client-side: 0:01, server-side: 0:01] [3 rows, 349B] [3 rows/s, 420B/s]

Query 20240117_194523_00009_vsd8a failed:  Cast from VARCHAR to DECIMAL(5, 2) is not supported cast((c0) as DECIMAL(5, 2))
```

**Comment by rui-mo** [comment]
Let me explain the context here. Casting from double/varchar to decimal are implemented in https://github.com/facebookincubator/velox/pull/5767 and https://github.com/facebookincubator/velox/pull/5307. They were both pended due to https://github.com/facebookincubator/velox/discussions/6323 but now `Status` is already merged in Velox. As offline communicated with @wuxueyang96 and @jinchengchenghh, I will continue to work on their pull requests.

- For cast from double to decimal, accoding to previous review, https://github.com/facebookincubator/velox/pull/6051 is needed. I plan to reopen it and rebase to it after it gets merged.
- For cast from varchar to decimal, we just merged Spark cast in Velox, so the compatibility issue with Presto can be resolved.

@mbasmanova @karteekmurthys Do you think above makes sense? Thanks.
cc @zhouyuan

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for clarifying. Makes sense to me.

**Comment by yzhang1991** [comment]
@aditi-pandit can you close this?
