### ISSUE TITLE
Nightly Jobs (Scheduled Jobs) are failing 

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#8966]
### Problem description

The nightly jobs (https://github.com/facebookincubator/velox/actions/workflows/scheduled.yml) are currently failing because they cannot load libboost 

```
error while loading shared libraries: libboost_context.so.1.84.0: cannot open shared object file: No such file or directory
```

### System information

See : https://github.com/facebookincubator/velox/actions/runs/8150420469/job/22277980506#step:5:22 

```
./spark_expression_fuzzer_test: error while loading shared libraries: libboost_context.so.1.84.0: cannot open shared object file: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by kgpai** [comment]
cc: @czentgr @majetideepak

**Comment by czentgr** [comment]
The setup script does not actually build the dependencies that may be required - this is expected because if the script is sourced it skips any build step.
So when the image was built to be used with the runner it likely has the shared library dependency (aka at built time it used the system install as opposed to the bundled version). And that dependency won't be installed by the script in the runner environment.
So I guess we will have to ensure that boost is statically linked.

Previously, boost on Ubuntu always came from the system package manager. But the new version is not present, hence it comes from the setup script.

How is fmt and folly handled? I looked at the yml but it wasn't clear how they are sourced.

Attempt at a fix: https://github.com/facebookincubator/velox/pull/8970

**Comment by majetideepak** [comment]
I described the fix here https://github.com/facebookincubator/velox/pull/8943

**Comment by mbasmanova** [comment]
I believe this is fixed.
