### ISSUE TITLE
Remove AggregationTestBase::allowInputShuffle_ member variable

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9274]
### Description

#9050 enhanced aggregation function registry to store order-sensitive metadata. This can be used to simplify AggregationTestBase by automatically discovering whether aggregate function is order-sensitive and therefore doesn't allow inputs to be shuffled.

CC: @duanmeng @kagamiori @kgpai

**Comment by yanngyoung** [comment]
Hi @mbasmanova I would like to take this first good issue, and have some background discussion with @duanmeng

**Comment by kgpai** [comment]
cc: @kevinwilfong

**Comment by mbasmanova** [comment]
@yanngyoung 

>  would like to take this first good issue

Please, go ahead. Thank you for the help.

**Comment by yanngyoung** [comment]
@mbasmanova Hi Masha, I'm checking the the background of  `orderSensitive` flag in #9050. I'm wondering if the ArbitraryAggregate's `orderSensitive` flag should be true as its result may be different for different input orders. The `testAggregations` would fail if the `testReadFromFiles` is enabled for `ArbitraryAggregate` when its `orderSensitive` flag is false. 

Should I fix it first and then proceed to investigate to use `orderSensitive` flag instead of the `allowInputShuffle` flag to enable testFromFiles? Could you please help to give some advice? Thanks!

**Comment by mbasmanova** [comment]
@yanngyoung Here is a definition of orderSensitive that I have in my mind. 

orderSensitive = false implies that aggregation produces same results regardless of the order of inputs. If input rows are shuffles randomly, the results are the same.

orderSensitive = true implies that aggregation results depend on the order of inputs. Same input rows presented in a different order may produce a different result. 

By this definition, arbitrary is order sensitive. min_by and max_by are also order sensitive (they produce different results in case of ties). I think it makes sense to mark these aggregates as such.

One wrinkle is that in Presto, arbitrary, min_by and max_by are not marked as order sensitive. This is confusing, especially since this doesn't allow user to control the order of inputs using min_by(x, y ORDER BY ...).

See https://github.com/prestodb/presto/issues/21786 and https://github.com/prestodb/presto/issues/21431

Perhaps, it is Ok for Velox to diverge from Presto on this.
