### ISSUE TITLE
Cannot cast VARCHAR '216821436-05-26' to DATE

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9381]
### Bug description

```
VeloxUserError:  Cannot cast VARCHAR '216821436-05-26' to DATE.  Unable to parse date value: "216821436-05-26".Valid date string pattern is (YYYY-MM-DD), and can be prefixed with [+-] cast((event_date) as DATE)
```

This works in Presto:

```
presto> select cast('216821436-05-26' as date);
     _col0
----------------
 +5155457-06-02
```

CC: @svm1 @aditi-pandit @kagamiori @amitkdutta 

### System information

n/a

**Comment by svm1** [comment]
@mbasmanova This issue is interesting. Although Java is indeed returning an actual value, it definitely doesn't appear correct - looks like some integer overflow is likely happening. 

I looked into the source code for this cast in Presto, which is using Java's own implementation for the conversion, via `java.sql.Date`. Neither Presto's Date-Time docs nor the Javadoc on the Date class specify any sort of constraint on the range of date values supported.

If anything, I see Velox handling this situation the right way - parsed dates are validated against a min and max year, and throw error if these boundaries are not met, as seen above. I think Presto's behavior should be corrected to constrain the range of dates supported. What do you think?

**Comment by mbasmanova** [comment]
CC: @Yuhta @pedroerp

**Comment by majetideepak** [comment]
I agree that Presto Java should implement proper bounds check and Velox is doing the right thing here.
Please re-open if there is a disagreement.

**Comment by pedroerp** [comment]
If anything, should we add a boundary check to java to ensure they have a consistent behavior?
